# Site settings
title: impractical.me
author: "Andrew Wessels"
email: shixish@gmail.com
description: "The personal website of Andrew Wessels."
baseurl: ""
url: "http://impractical.me"
twitter_username: shixish
github_username:  shixish

# Build settings
markdown: kramdown
permalink: pretty
pygments: true

# Define custom collections
collections:
  experiments:
    output: true
    permalink: /experiments/:path/
